# SPDX-FileCopyrightText: 2021 Danil Korennykh <bluskript@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
run:
  timeout: 5m
  skip-files:
    - ".*\\.pb\\.go"
    - ".*\\.hrpc\\.*.go"
issues:
  exclude-use-default: false
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - gomnd
    - tagliatelle
    # deprecated modules
    - golint
    - maligned
    - scopelint
    - interfacer
linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - "github.com/harmony-development/legato/*"
  stylecheck:
    dot-import-whitelist:
      - "github.com/harmony-development/legato/db/models"
  revive:
    rules:
      - name: dot-imports
        disabled: true
# wrapcheck:
# ignoreSigs:
# - api.NewError(
