// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"database/sql"
	"time"
)

type User struct {
	ID           uint64
	Username     string
	Avatar       *string
	UserStatus   int16
	Host         *string
	RemoteID     sql.NullInt64
	Email        *string
	PasswordHash []byte
	Created      time.Time
}
