package api

import harmonytypesv1 "github.com/harmony-development/legato/gen/harmonytypes/v1"

func meta(auth bool, local bool, owner bool, permissionNode string) *harmonytypesv1.HarmonyMethodMetadata {
	return &harmonytypesv1.HarmonyMethodMetadata{
		RequiresAuthentication: auth,
		RequiresLocal:          local,
		RequiresOwner:          owner,
		RequiresPermissionNode: permissionNode,
	}
}

var MethodMetadata = map[string]*harmonytypesv1.HarmonyMethodMetadata{
	"protocol.auth.v1.AuthService/Federate":       meta(false, false, false, ""),
	"protocol.auth.v1.AuthService/LoginFederated": meta(false, false, false, ""),
	"protocol.auth.v1.AuthService/Key":            meta(false, false, false, ""),
	"protocol.auth.v1.AuthService/BeginAuth":      meta(false, false, false, ""),
	"protocol.auth.v1.AuthService/NextStep":       meta(false, false, false, ""),
	"protocol.auth.v1.AuthService/StepBack":       meta(false, false, false, ""),
	"protocol.auth.v1.AuthService/StreamSteps":    meta(false, false, false, ""),
	"protocol.auth.v1.AuthService/CheckLoggedIn":  meta(true, false, false, ""),

	// TODO: correctly map this to the metadata in protocol
	"protocol.chat.v1.ChatService/CreateGuild":              meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/CreateRoom":               meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/CreateDirectMessage":      meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/UpgradeRoomToGuild":       meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/CreateInvite":             meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/CreateChannel":            meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetGuildList":             meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/InviteUserToGuild":        meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetPendingInvites":        meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/RejectPendingInvite":      meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/IgnorePendingInvite":      meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetGuild":                 meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetGuildInvites":          meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetGuildMembers":          meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetGuildChannels":         meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetChannelMessages":       meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetMessage":               meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/UpdateGuildInformation":   meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/UpdateChannelInformation": meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/UpdateChannelOrder":       meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/UpdateAllChannelOrder":    meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/UpdateMessageContent":     meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/DeleteGuild":              meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/DeleteInvite":             meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/DeleteChannel":            meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/DeleteMessage":            meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/JoinGuild":                meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/LeaveGuild":               meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/TriggerAction":            meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/SendMessage":              meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/HasPermission":            meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/SetPermissions":           meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetPermissions":           meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/MoveRole":                 meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetGuildRoles":            meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/AddGuildRole":             meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/ModifyGuildRole":          meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/DeleteGuildRole":          meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/ManageUserRoles":          meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetUserRoles":             meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/Typing":                   meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/PreviewGuild":             meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetBannedUsers":           meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/BanUser":                  meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/KickUser":                 meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/UnbanUser":                meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GetPinnedMessages":        meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/PinMessage":               meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/UnpinMessage":             meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/AddReaction":              meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/RemoveReaction":           meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GrantOwnership":           meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/GiveUpOwnership":          meta(true, false, false, ""),
	"protocol.chat.v1.ChatService/StreamEvents":             meta(true, false, false, ""),
}
